template = "https://github.com/giellalt/template-lang-und"
rev_id = 285
template_sha = "dc60d9e35b17842271a5a82c114510f9ff1a3d72"

[replacements]
__GLOTTOLOG_ID__ = "espe1235"
__REPO__ = "lang-epo"
__UND2C__ = "eo"
__UNDEFINED__ = "Esperanto"
__UND__ = "epo"
