template = "https://github.com/giellalt/template-lang-und"
rev_id = 331
template_sha = "8cacf2c4546a4e46881bd306e8c347aa8b1ae938"

[replacements]
__GLOTTOLOG_ID__ = "espe1235"
__REPO__ = "lang-epo"
__UND2C__ = "eo"
__UNDEFINED__ = "Esperanto"
__UND__ = "epo"
