template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "espe1235"
__REPO__ = "lang-epo"
__UND2C__ = "eo"
__UNDEFINED__ = "Esperanto"
__UND__ = "epo"
